apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
# - manifests/secret.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/statefulset.yaml
- manifests/service-client.yaml
- manifests/service-server.yaml
- manifests/ingress.yaml
- manifests/job.yaml
images:
- name: TODO/SERVER
  newName: jhiekkap/todo-server
- name: TODO/client
  newName: jhiekkap/todo-client
