apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: td
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        containers:
        - name: todo-server
          image: TODO-SERVER
        # - name: todo-server
        #   image: jhiekkap/todo-server:v2
          imagePullPolicy: Always
          env:
            - name: NODE_ENV
              value: production
        - name: todo-client
          image: TODO-CLIENT
        # - name: todo-client
        #   image: jhiekkap/todo-client:v1
          imagePullPolicy: Always
