apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mp-claim
  namespace: td
spec:
  # storageClassName: manual #(needed in k3d)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
